### ISSUE TITLE
Trouble running pod install

### ISSUE THREAD

**Issue by larrysalibra** [Casa/BlockstackBrowser-ios#25]
I'm using cocoapods `1.3.1` and xcode 9 beta 6 and `pod install` fails for me:

```
Vanquish:BlockstackBrowser-ios larry$ pod install
Analyzing dependencies
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, commit `9d6d16316edfb8ece47abebe1621d05ee6b0e6ed`

[!] Error installing Alamofire
[!] Failed to download 'Alamofire'.
Vanquish:BlockstackBrowser-ios larry$
```

**Comment by logansease** [comment]
I'll look into this. Looks like they remove the development branch I was using that supported swift 4 and this new version of xcode. I'll have to see where they merged that code

**Comment by logansease** [comment]
Hey Larry- i've added some info about this issue and a project setting that must be added to your local xcode copy to get around it. 

**First, in order to get my machine over the old alamofire installation, I had to completely clean the project pods by doing the following:**
- run a clean in xcode and then close xcode
- from the command line, in the project root folder run:
rm -rfd Pods/
rm -rfd BlockstackBrowser.xcworkspace
rm Podfile.lock
pod install

**Then follow the instructions found on the readme:**

_Because the dropbox sdk references a specific version of alamofire that is not compatible with swift 4, we must make a small change after running our pod install to get past a compile error in Alamofire's sdk._

- After running pod install and installing pods, open BlockstackBrowser.xcworkspace in Xcode9
- From the Project / File explorer on the left pane, select the Pods project, this will reveal all of the Pod targets, which are all of the pod libraries installed in the Browser.
- we need to customize the build seeings for the Alamofire library and get it to compile it with Swift 3.2, a backwards compatible version of swift 4. Start by selecting the AlamoFire library target.
- then select the build settings tab and use the search bar below it to search for the swift language version setting. Set it to Swift 3.2

**Comment by larrysalibra** [comment]
@logansease 

I followed these instructions:

```
run a clean in xcode and then close xcode
from the command line, in the project root folder run:
rm -rfd Pods/
rm -rfd BlockstackBrowser.xcworkspace
rm Podfile.lock
pod install
```
 The last one `pod install` still fails with the same error. I don't have an existing install of AlamoFire. :-/

**Comment by logansease** [comment]
just to make sure... I pushed an update to the podfile, so you did a git pull first, right?

**Comment by logansease** [comment]
if not, please do that. If so, please also do a 'pod repo update' to make sure your local repo is up to date.

**Comment by larrysalibra** [comment]
Thanks @logansease ! I got it running successfully in the simulator! Playing around now.
